<<<<<<< HEAD
# Site settings
title: Butane Jekyll Theme
description: >
    This is an example of the Butane Jekyll Theme created by Alex Carpenter
author: Alex Carpenter
email: youemail@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://alexcarpenter.github.io" # the base hostname & protocol for your site
twitter_username: hybrid_alex
github_username:  alexcarpenter

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title
sass:
    style: compressed
=======

##
# RLStevenson Theme Options
####

# For baseurl:
# Use '' for / or '/your-dir' for another directory

title:		RLStevenson
description:	'A Bootstrap based clone of the Hyde theme by mdo.'
freetext:	'Released under an MIT license - feel free to make pull requests.'
baseurl:	'/'
paginate:	3
version:	0.1.0
colorscheme:	scheme-gulfracing

ga:		'UA-123-456'
piwikSiteID:	''
piwikURL:	''

author:
 url:		https://www.exchangerate-api.com
 name:		'ExchangeRate-API'

github:
 repo:		https://github.com/ExchangeRate-API/rlstevenson-jekyll-theme

gems:		[jekyll-paginate]

exclude:	['README.md', 'Gemfile.lock', 'Gemfile', '*.gemspec', '*.gem']

theme: jekyll-theme-slate
>>>>>>> e7cad6d98c2a2ec09c4ee32b86b8fae4acc6ab26
