name: Shuai Guo
url: https://shuaiguo95.github.io/
description: Dalian University of Technology

permalink: /:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
